from typing import Protocol
from app.modules.listings.models import Listing, ListingStatus


class ListingRepository(Protocol):
    async def get(self, id: int) -> Listing | None: ...
    async def list_recent(self, limit: int = 24, status: ListingStatus = ListingStatus.ACTIVE) -> list[Listing]: ...
    async def get_by_external(self, source_id: int, external_id: str) -> Listing | None: ...
    async def add(self, listing: Listing) -> Listing: ...
    async def update_translations(self, id: int, descriptions: dict[str, str]) -> None: ...
