from typing import Protocol
from app.modules.sources.models import Source, SourceType


class SourceRepository(Protocol):
    async def get(self, id: int) -> Source | None: ...
    async def get_by_name(self, type: SourceType, name: str) -> Source | None: ...
    async def list_active(self, type: SourceType | None = None) -> list[Source]: ...
    async def upsert(self, source: Source) -> Source: ...
    async def mark_scraped(self, id: int) -> None: ...
