from typing import Protocol
from app.modules.users.models import User


class UserRepository(Protocol):
    async def get(self, id: int) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def add(self, user: User) -> User: ...
