"""init schema

Revision ID: db3706c80c01
Revises: 
Create Date: 2026-04-27 22:38:13.690054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3706c80c01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_me', sa.String(length=128), nullable=False),
    sa.Column('name_ru', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('NATIVE', 'TELEGRAM', 'FACEBOOK', 'OLX', 'MOJKVADRAT', name='source_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_lang', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('title_translations', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_translations', sa.JSON(), nullable=False),
    sa.Column('original_lang', sa.String(length=8), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=8), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('contact_telegram', sa.String(length=128), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('contact_facebook', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'HIDDEN', 'SOLD', 'ARCHIVED', name='listing_status'), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_dedup_hash'), ['dedup_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_slug'), ['slug'], unique=False)
        batch_op.create_index('ix_listings_source_external', ['source_id', 'external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_listings_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    op.create_table('listing_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('original_url', sa.String(length=1024), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('phash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_images_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_images_phash'), ['phash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_images_phash'))
        batch_op.drop_index(batch_op.f('ix_listing_images_listing_id'))

    op.drop_table('listing_images')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_index(batch_op.f('ix_listings_source_id'))
        batch_op.drop_index('ix_listings_source_external')
        batch_op.drop_index(batch_op.f('ix_listings_slug'))
        batch_op.drop_index(batch_op.f('ix_listings_dedup_hash'))
        batch_op.drop_index(batch_op.f('ix_listings_city'))
        batch_op.drop_index(batch_op.f('ix_listings_category_id'))
        batch_op.drop_index(batch_op.f('ix_listings_author_user_id'))

    op.drop_table('listings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_name'))

    op.drop_table('sources')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))

    op.drop_table('categories')
    # ### end Alembic commands ###
