from typing import Protocol
from app.modules.messaging.models import Conversation, Message


class MessagingRepository(Protocol):
    async def get_conversation(self, id: int) -> Conversation | None: ...
    async def find_conversation(self, listing_id: int, buyer_id: int) -> Conversation | None: ...
    async def create_conversation(self, conv: Conversation) -> Conversation: ...
    async def list_user_conversations(self, user_id: int) -> list[Conversation]: ...
    async def add_message(self, msg: Message) -> Message: ...
    async def list_messages(self, conversation_id: int) -> list[Message]: ...
    async def touch_conversation(self, conversation_id: int) -> None: ...
