from typing import Protocol
from app.modules.catalog.models import Category


class CategoryRepository(Protocol):
    async def list_roots(self) -> list[Category]: ...
    async def get_by_slug(self, slug: str) -> Category | None: ...
    async def get(self, id: int) -> Category | None: ...
